package dev.goquick.kmpertrace

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Task that writes a generated Kotlin source file based on the [KmperTraceExtension] settings.
 */
abstract class GenerateKmperTraceTask : DefaultTask() {

    @get:Input
    /**
     * Package name used for the generated source.
     */
    abstract val packageName: Property<String>

    @get:Input
    /**
     * Class name used for the generated source.
     */
    abstract val className: Property<String>

    @get:Input
    /**
     * Message assigned to the generated `MESSAGE` constant.
     */
    abstract val message: Property<String>

    @get:OutputDirectory
    /**
     * Destination directory where generated sources are written.
     */
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    /**
     * Generate the Kotlin source file into [outputDirectory].
     */
    fun generate() {
        val pkg = packageName.get()
        val cls = className.get()
        val msg = message.get()

        val targetDir = outputDirectory.get().dir(pkg.replace('.', '/')).asFile
        targetDir.mkdirs()

        val file = targetDir.resolve("$cls.kt")
        val escapedMessage = msg.replace("\"", "\\\"")
        file.writeText(
            """
            |// Generated by dev.goquick.kmpertrace at ${java.time.Instant.now()}
            |package $pkg
            |
            |class $cls {
            |    companion object {
            |        const val MESSAGE: String = "$escapedMessage"
            |    }
            |}
            |
            """.trimMargin()
        )
    }
}
